apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-dqvh
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0074-tenant/tkrw-pr712-0075-0074-app/devfile-sample-dqvh@sha256:5e35e7a2d769d9b4bb598da98c96867c9ebb21d071ef3094a7b5ca96356a328d
        name: my-nodejs
        resources: {}
status: {}
